/*
 * Copyright (c) 2026 Pavel Castornii. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation. This particular file is
 * subject to the "Classpath" exception as provided in the LICENSE file
 * that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */

package com.techsenger.statefx.mavenplugin;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 *
 * @author Pavel Castornii
 */
final class StateGenerator {

    private static final String CORE_PACKAGE = "com.techsenger.statefx.core";

    private static final String HEADER =
            """
            /*
             * Generated by StateFX Maven Plugin.
             *
             * DO NOT EDIT THIS FILE MANUALLY!
             */

            package com.techsenger.statefx.states;

            """;

    private static final String INSET = "    ";

    static void generateMap(Path packagePath, ContainerMeta map) throws IOException {
        var className = map.getType().getSimpleName().substring("Observable".length())
                + map.getCapitalizedName() + "State";
        var rwClassName = "RW" + className;
        generateMapState(packagePath, map, className, null, false);
        generateMapState(packagePath, map, rwClassName, className, true);
    }

    static void generateCollection(Path packagePath, ContainerMeta collection) throws IOException {
        var className = collection.getType().getSimpleName().substring("Observable".length())
                + collection.getCapitalizedName() + "State";
        var rwClassName = "RW" + className;
        generateCollectionState(packagePath, collection, className, null, false);
        generateCollectionState(packagePath, collection, rwClassName, className, true);
    }

    static void generateProperty(Path packagePath, PropertyMeta property) throws IOException {
        var className = property.getWrapperType() + property.getCapitalizedName() + "State";
        var roClassName = "RO" + className;
        generateRoPropertyState(packagePath, property, roClassName);
        generatePropertyState(packagePath, property, className, roClassName);
    }

    private static void generateMapState(Path packagePath, ContainerMeta map,
            String className, String rwParentClassName, boolean rw) throws IOException {
        StringBuilder builder = new StringBuilder();
        builder.append(HEADER);

        if (!rw) {
            builder.append("import ");
            builder.append(CORE_PACKAGE);
            builder.append(".MapState;");
            builder.append(System.lineSeparator());
        }
        builder.append("import ");
        builder.append(map.getType().getName());
        builder.append(";");
        builder.append(System.lineSeparator());
        builder.append(System.lineSeparator());

        builder.append("public interface ");
        builder.append(className);
        builder.append("<T, S>");
        builder.append(" extends ");
        if (rw) {
            builder.append(rwParentClassName);
        } else {
            builder.append("MapState");
        }
        builder.append(" {");
        builder.append(System.lineSeparator());
        builder.append(System.lineSeparator());

        builder.append(INSET);
        builder.append(map.getType().getSimpleName());
        builder.append("<T, S>");
        builder.append(" get");
        if (rw) {
            builder.append("Modifiable");
        }
        builder.append(map.getCapitalizedName());
        builder.append("();");
        builder.append(System.lineSeparator());

        builder.append("}");
        builder.append(System.lineSeparator());

        Files.writeString(packagePath.resolve(className + ".java"), builder.toString());
    }

    private static void generateCollectionState(Path packagePath, ContainerMeta collection,
            String className, String rwParentClassName, boolean rw) throws IOException {
        StringBuilder builder = new StringBuilder();
        builder.append(HEADER);

        if (!rw) {
            builder.append("import ");
            builder.append(CORE_PACKAGE);
            builder.append(".CollectionState;");
            builder.append(System.lineSeparator());
        }
        builder.append("import ");
        builder.append(collection.getType().getName());
        builder.append(";");
        builder.append(System.lineSeparator());
        builder.append(System.lineSeparator());

        builder.append("public interface ");
        builder.append(className);
        builder.append("<T>");
        builder.append(" extends ");
        if (rw) {
            builder.append(rwParentClassName);
        } else {
            builder.append("CollectionState");
        }
        builder.append(" {");
        builder.append(System.lineSeparator());
        builder.append(System.lineSeparator());

        builder.append(INSET);
        builder.append(collection.getType().getSimpleName());
        builder.append("<T>");
        builder.append(" get");
        if (rw) {
            builder.append("Modifiable");
        }
        builder.append(collection.getCapitalizedName());
        builder.append("();");
        builder.append(System.lineSeparator());

        builder.append("}");
        builder.append(System.lineSeparator());

        Files.writeString(packagePath.resolve(className + ".java"), builder.toString());
    }

    private static void generateRoPropertyState(Path packagePath, PropertyMeta property,
            String className) throws IOException {
        StringBuilder builder = new StringBuilder();
        builder.append(HEADER);

        builder.append("import ");
        builder.append(CORE_PACKAGE);
        builder.append(".PropertyState;");
        builder.append(System.lineSeparator());
        builder.append("import ");
        builder.append(property.getReadOnlyType().getName());
        builder.append(";");
        builder.append(System.lineSeparator());
        builder.append(System.lineSeparator());

        builder.append("public interface ");
        builder.append(className);
        builder.append(property.getGenericParameter());
        builder.append(" extends ");
        builder.append("PropertyState {");
        builder.append(System.lineSeparator());
        builder.append(System.lineSeparator());

        builder.append(INSET);
        builder.append(property.getReadOnlyType().getSimpleName());
        builder.append(property.getGenericParameter());
        builder.append(" ");
        builder.append(property.getName());
        builder.append("Property();");
        builder.append(System.lineSeparator());
        builder.append(System.lineSeparator());

        builder.append(INSET);
        builder.append(property.getValueType());
        builder.append(" ");
        builder.append(property.getGetterPrefix());
        builder.append(property.getCapitalizedName());
        builder.append("();");
        builder.append(System.lineSeparator());

        builder.append("}");
        builder.append(System.lineSeparator());

        Files.writeString(packagePath.resolve(className + ".java"), builder.toString());
    }

    private static void generatePropertyState(Path packagePath, PropertyMeta property, String className,
            String roClassName) throws IOException {
        var builder = new StringBuilder();
        builder.append(HEADER);

        builder.append("import ");
        builder.append(property.getType().getName());
        builder.append(";");
        builder.append(System.lineSeparator());
        builder.append(System.lineSeparator());

        builder.append("public interface ");
        builder.append(className);
        builder.append(property.getGenericParameter());
        builder.append(" extends ");
        builder.append(roClassName);
        builder.append(property.getGenericParameter());
        builder.append(" {");
        builder.append(System.lineSeparator());
        builder.append(System.lineSeparator());

        builder.append(INSET);
        builder.append("@Override");
        builder.append(System.lineSeparator());
        builder.append(INSET);
        builder.append(property.getType().getSimpleName());
        builder.append(property.getGenericParameter());
        builder.append(" ");
        builder.append(property.getName());
        builder.append("Property();");
        builder.append(System.lineSeparator());
        builder.append(System.lineSeparator());

        builder.append(INSET);
        builder.append("void set");
        builder.append(property.getCapitalizedName());
        builder.append("(");
        builder.append(property.getValueType());
        builder.append(" value);");
        builder.append(System.lineSeparator());

        builder.append("}");
        builder.append(System.lineSeparator());

        Files.writeString(packagePath.resolve(className + ".java"), builder.toString());
    }

    private StateGenerator() {
        // empty
    }
}
